# Generated by Django 5.0.6 on 2025-02-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_ip',
            field=models.GenericIPAddressField(null=True, verbose_name='Last IP Address'),
        ),
    ]
