# Generated by Django 5.0.6 on 2025-02-27 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_last_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Role name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Last IP Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.role', verbose_name='Role'),
        ),
    ]
