# Generated by Django 5.0.6 on 2025-02-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adderss', models.GenericIPAddressField(blank=True, null=True, verbose_name="Visitor's ip")),
                ('user_agent', models.CharField(blank=True, max_length=10, null=True, verbose_name='agent')),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('referrer', models.URLField(blank=True, null=True, verbose_name='referrer')),
                ('path', models.CharField(max_length=255)),
                ('duration', models.IntegerField(default=0)),
            ],
        ),
    ]
